### ISSUE TITLE
Yea no.

### ISSUE THREAD

**Issue by ImInTheICU** [AMIR-H-P/Discord-Nuker#13]
I dont suggest using this as its obfuscated, just find a safe and open-source one.

**Comment by 6nz** [comment]
its open sourced

**Comment by 6nz** [comment]
https://github.com/6nz/Decompiled-and-Deobfuscated-stuff/tree/main/Nukers/Discord-Nuker-13

**Comment by ImInTheICU** [comment]
So what?
you copied that one added hazer logger than obfuscated it?

**Comment by 6nz** [comment]
> So what?
> you copied that one added hazer logger than obfuscated it?
> 

?

**Comment by 6nz** [comment]
Copied what, thats the actual deobfuscated code
