### ISSUE TITLE
Check bootstrap restrict mode failed

### ISSUE THREAD

**Issue by Bananduck** [AMIR-H-P/Discord-Nuker#14]
I just run the setup.bat and I try to run run.bat and it said this:
![image](https://github.com/AMIR-H-P/Discord-Nuker/assets/98893840/6c33e3ab-8772-44a9-84e3-a1b556e4d515)
how do i fix it

**Comment by gumbobr0t** [comment]
its malware lil bro check the main.py looks legitimate right?

**Comment by AMIR-H-P** [comment]
> its malware lil bro check the main.py looks legitimate right?
This program has been tested by many antiviruses and does not pose a security risk @gumbobr0t

**Comment by gumbobr0t** [comment]
> > its malware lil bro check the main.py looks legitimate right?
> This program has been tested by many antiviruses and does not pose a security risk @gumbobr0t 
> 

dude what? its pyarmor obfuscated, if it is so secure, why dont you just provide the fucking source? github is for OPEN SOURCE PROJECTS idiots, stop spreading your shitty malware
