### ISSUE TITLE
IT CONTAINS MALWARE

### ISSUE THREAD

**Issue by Miercoe** [AMIR-H-P/Discord-Nuker#15]
bro we not stupid

**Comment by AMIR-H-P** [comment]
It was a good joke 😂 

This version is defunct and you should know that no antivirus will suspect this program. Do you know why ? Because you talk without a convincing reason and you have no evidence. I said this program is not a virus. If it was a virus, would it get 75 stars? 
**Use brain**

**Comment by ingoau** [comment]
> If it was a virus, would it get 75 stars?

https://www.followdeh.com/en/github/stars

**Comment by Miercoe** [comment]
I don't know how GitHub allows encripted content they have to show the source code to prove
