### ISSUE TITLE
Source code here :)

### ISSUE THREAD

**Issue by 6nz** [AMIR-H-P/Discord-Nuker#2]

**Comment by 6nz** [comment]
### Problems:
**1: Trash obfuscation**
**2: Low speed nuker bc no threading**
**3: Not using discord API lmao**
**4: Owner can't code and this nuker is probably skidded😂**
Marci✅

**Comment by 15yrold** [comment]
Damn, Bro got violated & Cyber Bullied onGitHub 😂 😂

**Comment by 6nz** [comment]
why are u using print() instead of \n LMFAO

**Comment by 6nz** [comment]
putting print() after every line LOOLL

**Comment by 6nz** [comment]
u can't even make a starting animation 😂😂😂😂😂😂😂😂😂

**Comment by 6nz** [comment]
```python
@bot.event
async def on_ready():
    Clearr()
    print(
        f'STARTING : [{b}■■■                       {w}]  {b}1{w}/{b}10 {w}({b}10.00%{w})')
    await asyncio.sleep(0.5)
    Clearr()
    print(
        f'STARTING : [{b}■■■■■■                    {w}]  {b}2{w}/{b}10 {w}({b}20.00%{w})')
    await asyncio.sleep(0.5)
    Clearr()
    print(
        f'STARTING : [{b}■■■■■■■■■■■               {w}]  {b}4{w}/{b}10 {w}({b}40.00%{w})')
    await asyncio.sleep(0.5)
    Clearr()
    print(
        f'STARTING : [{b}■■■■■■■■■■■■■■■■          {w}]  {b}6{w}/{b}10 {w}({b}60.00%{w})')
    await asyncio.sleep(0.5)
    Clearr()
    print(
        f'STARTING : [{b}■■■■■■■■■■■■■■■■■■■■      {w}]  {b}8{w}/{b}10 {w}({b}80.00%{w})')
    await asyncio.sleep(0.5)
    Clearr()
    print(
        f'STARTING : [{b}■■■■■■■■■■■■■■■■■■■■■■■■■■{w}]  {b}10{w}/{b}10 {w}({b}100.00%{w})')
    await asyncio.sleep(0.5)
    Clearr()
```
**What the hell is this 😂😂😂**

**Comment by logicguy1** [comment]
Lmao i also just dropped it in a VM to decode shit ass obfuscation, i see this all the time with people trying to "hide" their souce
The only respected method of obfuscation is manual

**Comment by logicguy1** [comment]
All you need to do is change the last line to
```print(base64.b64decode(eval('\x74\x72\x75\x73\x74')).decode())```
and it will dump the whole source code in the console

**Comment by 6nz** [comment]
> 
agree
