### ISSUE TITLE
.

### ISSUE THREAD

**Issue by 6nz** [AMIR-H-P/Discord-Nuker#6]
https://github.com/6nz/Decompiled-and-Deobfuscated-stuff

**Comment by JokersCat** [comment]
How?

**Comment by AMIR-H-P** [comment]
@6nz  ok

**Comment by 6nz** [comment]
> @6nz  I need your help =|
> can you help me? 

?

**Comment by 6nz** [comment]
> How?

Skill.

**Comment by AMIR-H-P** [comment]
> > How?
> 
> Skill.

https://github.com/Atropate-cod/Discord-Mass-Ban Token Grabber???

**Comment by AMIR-H-P** [comment]
> > @6nz  I need your help =|
> > can you help me?
> 
> ?

https://github.com/Atropate-cod/Discord-Mass-Ban Token Grabber?

**Comment by AMIR-H-P** [comment]
> > > @6nz  I need your help =|
> > > can you help me?
> > 
> > 
> > ?
> 
> https://github.com/Atropate-cod/Discord-Mass-Ban Token Grabber?

Can you send me  deobf this file?

**Comment by 6nz** [comment]
> > > > @6nz  I need your help =|
> > > > can you help me?
> > > 
> > > 
> > > ?
> > 
> > 
> > https://github.com/Atropate-cod/Discord-Mass-Ban Token Grabber?
> 
> Can you send me deobf this file?

ye

**Comment by 6nz** [comment]
i will send it sec

**Comment by AMIR-H-P** [comment]
> i will send it sec

broh hoooww

**Comment by 6nz** [comment]
https://github.com/6nz/Decompiled-and-Deobfuscated-stuff/tree/main/Nukers/Discord-Mass-Ban

**Comment by 6nz** [comment]
here

**Comment by AMIR-H-P** [comment]
> here

Howw
pls tell =|

**Comment by 6nz** [comment]
forgot to add some files @AMIR-H-P check repo again

**Comment by 6nz** [comment]
now fully fixed, added core folder

**Comment by 6nz** [comment]
> > here
> 
> Howw pls tell =|

Skill. i am a professional programmer

**Comment by AMIR-H-P** [comment]
> forgot to add some files @AMIR-H-P check repo again

Pls tell me :(

**Comment by AMIR-H-P** [comment]
tools ??? @6nz

**Comment by 6nz** [comment]
i make my own deobfuscator tools

**Comment by AMIR-H-P** [comment]
> i make my own deobfuscator tools

👀🤭Niceeee

**Comment by AMIR-H-P** [comment]
What is your advice to me? @6nz

**Comment by AMIR-H-P** [comment]
Also, I'm not very good at Python 

> What is your advice to me? @6nz

Also, I'm not as Very good at Python🙄

**Comment by 6nz** [comment]
> advice

?

**Comment by AMIR-H-P** [comment]
> 

exhortation

**Comment by 6nz** [comment]
😂

**Comment by AMIR-H-P** [comment]
> 😂

:\
