### ISSUE TITLE
why obsucated? 

### ISSUE THREAD

**Issue by RaidFourms** [AMIR-H-P/Discord-Nuker#9]
seriously, why?

**Comment by AMIR-H-P** [comment]
> seriously, why?

Hello @RaidFourms 👋.  Because I do not want some people to copy it and use it in their own name.

and If you have a better idea, you can contact me here ؛)

**Comment by RaidFourms** [comment]
> 

yes.
make it open source, which is the entire point of github.

**Comment by AMIR-H-P** [comment]
> > 
> 
> yes.
> make it open source, which is the entire point of github.

Sure. 
I think about it.  Because your comments are important to me

**Comment by AstroOnYT** [comment]
> > 
> 
> yes. make it open source, which is the entire point of github.

bro you can easily deobfuscate pyarmor i might do it but im to lazy but search up pyarmor deobfuscators on github

**Comment by 6nz** [comment]
> > 
> 
> yes. make it open source, which is the entire point of github.

Decompiled source is on my github. https://github.com/6nz/Decompiled-and-Deobfuscated-stuff/tree/main/Nukers/Discord-Nuker-13
@RaidFourms 👍

**Comment by AMIR-H-P** [comment]
bruuub @6nz 🙄

**Comment by 6nz** [comment]
> bruuub @6nz 🙄

Nah why u trying to hide it

**Comment by AMIR-H-P** [comment]
please wait @6nz

**Comment by AMIR-H-P** [comment]
https://github.com/6nz/Decompiled-and-Deobfuscated-stuff

**Comment by AMIR-H-P** [comment]
Enough? @6nz

**Comment by 6nz** [comment]
Bruh

**Comment by AMIR-H-P** [comment]
> Bruh

🙄
